FROM python:3.12-slim

WORKDIR /app

# System deps
RUN apt-get update && apt-get install -y libpq-dev gcc curl iputils-ping && rm -rf /var/lib/apt/lists/*

# Python deps
COPY code/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy Code (overridden by volume in dev but useful for prod)
COPY code /app

# Default command (can be overridden)
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "9000"]
