# ticketera/backend/services/service/__init__.py
"""
Service package — re-exports everything from submodules to preserve the original
service.py public interface.

Consumers use:
    from ticketera.backend.services import service as tickets_service
    tickets_service.some_function()

All names (public and private) must be available at this module level.

Module split:
    _helpers.py        — constants and pure utility functions
    _classify.py       — auto-classification/assignment
    _notifications.py  — channel notifications dispatch
    _crud.py           — main ticket CRUD (orchestrator)
    _sla.py            — SLA/compliance/evidence
    _specialties.py    — specialty management
    _email.py          — incoming email processing
    _customers.py      — client association/directory
"""

# ── _helpers: constants, classes, and pure utility functions ─────────────────
from ._helpers import (  # noqa: F401
    # Classes
    ConflictError,
    _IncomingEmailHtmlSanitizer,

    # Constants
    CATEGORIAS_VALIDAS,
    ESTADOS_VALIDOS,
    MAIN_STATUS_SEQUENCE,
    SEVERIDADES_VALIDAS,
    ROLES_TECNICOS,
    ROLES_TECNICOS_SET,
    ROLES_ADMIN_GESTION,
    ROLES_DESPACHO_MESA,
    HELPDESK_MANAGER_ROLE,
    TICKET_SECURITY_CLASSES,
    TIPOS_TICKET_VALIDOS,
    SUBESTADOS_VALIDOS,
    SUBESTADOS_ESPERA,
    SUBESTADOS_LEGACY_MAP,
    ROLE_SPECIALTY_FALLBACK,
    AUTO_REPLY_SLA_MINUTES,
    ASSIGNMENT_SLA_MINUTES,
    RESOLUTION_SLA_MINUTES,
    SLA_STORAGE_HOURS,
    SLA_HORAS,
    PRIORIDAD_MAP,
    FRT_MINUTOS,
    TTR_MINUTOS,
    TICKET_PUBLIC_CODE_START,
    CHAIN_ALGO,
    CHAIN_VERSION,
    EMAIL_DRAFT_LOCK_MINUTES,
    EMAIL_DRAFT_LOCK_HEARTBEAT_SECONDS,
    TICKET_READONLY_ESTADOS,
    TICKET_EMAIL_ALLOWED_ESTADOS,
    TICKET_EMAIL_BLOCKED_ESTADOS,
    REPLY_BLOCKED_ESTADOS,
    INCOMING_EMAIL_ALLOWED_TAGS,
    INCOMING_EMAIL_VOID_TAGS,
    INCOMING_EMAIL_DROP_TAGS,
    INCOMING_EMAIL_ALLOWED_ATTRS,
    SLA_MODE,
    SLA_BUSINESS_TZ,
    SLA_BUSINESS_DAYS,
    SLA_BUSINESS_START_HOUR,
    SLA_BUSINESS_END_HOUR,
    SLA_ESCALATION_WINDOWS_PCT,
    RESUELTO_AUTO_CLOSE_HOURS,
    COMPLIANCE_TZ,
    COMPLIANCE_EXPORT_DIR,
    COMPLIANCE_EXPORT_HOUR,
    COMPLIANCE_PURGE_HOUR,
    COMPLIANCE_EXPORT_MINUTE,
    COMPLIANCE_PURGE_MINUTE,
    COMPLIANCE_PURGE_GRACE_DAYS,
    RETENTION_POLICY_DAYS,
    CHANNEL_NOTIFICATION_STATUSES,
    CHANNEL_ADAPTER_MODES,
    CHANNELS_ENABLED,
    CHANNELS_MAX_ATTEMPTS,
    CHANNELS_RETRY_BASE_SECONDS,
    CHANNELS_RETRY_MAX_SECONDS,
    WORKFLOW_RULES,
    AUTO_REPLY_MAX_REFERENCES,
    EMAIL_ROUTE_MATCH_TYPES,
    AUTO_REPLY_SUBJECT_SETTING_KEY,
    AUTO_REPLY_BODY_SETTING_KEY,
    HELPDESK_NEW_TICKET_SUBJECT_SETTING_KEY,
    HELPDESK_NEW_TICKET_BODY_SETTING_KEY,
    CLIENT_ASSIGNMENT_SUBJECT_SETTING_KEY,
    CLIENT_ASSIGNMENT_BODY_SETTING_KEY,
    SPECIALIST_ASSIGNMENT_SUBJECT_SETTING_KEY,
    SPECIALIST_ASSIGNMENT_BODY_SETTING_KEY,
    RESOLUTION_SUBJECT_SETTING_KEY,
    RESOLUTION_BODY_SETTING_KEY,
    MAIL_TEMPLATE_KEY_AUTO_REPLY,
    MAIL_TEMPLATE_KEY_HELPDESK_NEW_TICKET,
    MAIL_TEMPLATE_KEY_CLIENT_ASSIGNMENT,
    MAIL_TEMPLATE_KEY_SPECIALIST_ASSIGNMENT,
    MAIL_TEMPLATE_KEY_RESOLUTION,
    DEFAULT_REPLY_SUBJECT_TEMPLATE,
    DEFAULT_AUTO_REPLY_BODY_TEMPLATE,
    DEFAULT_HELPDESK_NEW_TICKET_SUBJECT_TEMPLATE,
    DEFAULT_HELPDESK_NEW_TICKET_BODY_TEMPLATE,
    DEFAULT_CLIENT_ASSIGNMENT_BODY_TEMPLATE,
    DEFAULT_SPECIALIST_ASSIGNMENT_SUBJECT_TEMPLATE,
    DEFAULT_SPECIALIST_ASSIGNMENT_BODY_TEMPLATE,
    DEFAULT_RESOLUTION_BODY_TEMPLATE,
    TICKETERA_MAIL_TEMPLATE_DEFS,
    KEYWORDS_CATEGORIAS,

    # Public helper functions
    normalize_ticket_security_class,
    normalize_ticket_type,
    normalize_subestado,
    list_ticketera_mail_templates,
    get_monthly_report_data,
    get_ticketera_mail_template,
    update_ticketera_mail_template,
    get_ticketera_templates,
    update_ticketera_templates,
    list_ticketera_routing_rules,
    upsert_ticketera_routing_rule,
    delete_ticketera_routing_rule,
    get_ticketera_admin_config,
    notify_client_assignment,
    notify_specialist_assignment,
    notify_helpdesk_new_ticket,
    estado_from_subestado,
    normalize_adapter_mode,
    normalize_channel_name,
    normalize_notification_status,

    # Private helper functions
    _clamp_int,
    _parse_business_days,
    _parse_escalation_windows,
    _parse_tz_offset,
    _parse_timezone_name,
    _default_compliance_export_dir,
    _default_ticket_attachments_dir,
    _channels_enabled,
    _attachment_roots,
    _is_safe_attachment_path,
    _attachment_storage_name,
    _parse_csv_lower_set,
    _normalize_email_address,
    _extract_email_domain,
    _normalize_email_route_match_value,
    _get_system_setting,
    _upsert_system_setting,
    _sender_identity,
    _format_sla_minutes_label,
    _ticket_sla_summary_label,
    _auto_reply_delay_minutes,
    _auto_reply_require_allowlist,
    _auto_reply_allowlist_emails,
    _auto_reply_allowlist_domains,
    _auto_reply_blocked_localparts,
    _auto_reply_sender_allowed,
    _auto_reply_idempotency_key,
    _normalize_roles,
    _normalize_role,
    _normalize_username,
    _parse_secondary_roles_value,
    _scope_enforced,
    _is_admin_management_role,
    _is_tech_role,
    _is_dispatcher_role,
    _can_dispatch_reassign,
    _ticket_assignee_username,
    _ensure_can_manage_ticket,
    _ensure_can_participate_ticket,
    _is_reply_blocked_by_estado,
    _db_bool,
    _ticket_is_trashed,
    _ticket_display_status,
    _is_readonly_blocked_by_estado,
    _ensure_ticket_not_trashed,
    _ensure_reply_allowed_estado,
    _ensure_can_manage_ticket_trash,
    _extract_ticket_target_email,
    _tokenize_email_values,
    _normalize_notify_emails,
    _serialize_notify_emails,
    _notify_emails_from_ticket,
    _normalize_recipient_emails,
    _render_text_template,
    _format_assignee_name,
    _ticketera_template_context,
    _append_specialist_sla_note,
    _get_ticketera_mail_template_def,
    _serialize_ticketera_mail_template,
    _ticketera_template_text_to_html,
    _render_ticketera_mail_subject,
    _render_ticketera_mail_body_html,
    _render_ticketera_mail_template,
    _serialize_email_route_row,
    _resolve_routing_category_for_email,
    _compose_reply_recipients,
    _resolve_helpdesk_new_ticket_recipients,
    _estado_label,
    _send_ticket_status_update_to_notify_emails,
    _build_ticket_reply_subject,
    _hash_draft_lock_token,
    _lock_expiry_iso,
    _is_draft_lock_active,
    _draft_lock_info,
    _new_draft_lock_token,
    _drafts_base_path,
    _channel_adapter_mode,
    _channel_provider_name,
    _channel_retry_delay_seconds,
    _enqueue_job_async_safe,
    _stable_json,
    _build_chain_hash,
    _retention_days_for_class,
    _retention_until_iso,
    _recompute_ticket_retention,
    _sha256_file,
    _parse_dt,
    _now_dt,
    _ensure_utc,
    _business_bounds,
    _is_business_day,
    _align_to_business_start,
    _add_business_minutes,
    _frt_due_iso,
    _ttr_due_iso,
)

# ── _classify: auto-classification and auto-assignment ───────────────────────
from ._classify import (  # noqa: F401
    clasificar_ticket,
    auto_asignar,
    incrementar_carga,
    decrementar_carga,
)

# ── _notifications: escalated notifications and channel dispatch ─────────────
from ._notifications import (  # noqa: F401
    programar_notificaciones,
    marcar_notificacion_vista,
    get_notificaciones_pendientes,
    log_notification_attempt,
    notify_client_resolution,
    process_pending_notifications,
    _get_auto_close_hours,
    _schedule_next_process_notifications,
    get_jobs_queue_health,
    get_channels_status,
    list_channel_notifications,
    retry_channel_notification,
)

# ── _specialties: specialty management ───────────────────────────────────────
from ._specialties import (  # noqa: F401
    list_specialties,
    upsert_specialty,
    toggle_availability,
    delete_specialty,
    _resolve_role_specialties,
    _active_ticket_load_map,
    _list_specialties_with_role_fallback,
)

# ── _sla: SLA metrics, compliance, evidence, legal holds ─────────────────────
from ._sla import (  # noqa: F401
    get_sla_metrics,
    list_sla_breaches,
    upsert_automation_rule,
    list_automation_rules,
    create_evidence_event,
    list_evidence_events,
    list_ticket_legal_holds,
    create_ticket_legal_hold,
    release_ticket_legal_hold,
    run_compliance_export,
    list_compliance_export_runs,
    run_compliance_purge,
    list_compliance_purge_runs,
    verify_hash_chain,
    _normalize_iso_utc,
    _normalize_compliance_scope,
    _artifact_exists_with_hash,
    _compliance_run_duplicate_decision,
    _retention_case_sql,
    _list_purge_candidates,
)

# ── _crud: main ticket CRUD orchestrator ─────────────────────────────────────
from ._crud import (  # noqa: F401
    generar_codigo,
    run_sla_evaluation_batch,
    create_ticket,
    get_ticket,
    list_tickets,
    claim_ticket,
    update_ticket,
    move_ticket_to_trash,
    restore_ticket_from_trash,
    add_comment,
    get_ticket_email_draft,
    acquire_ticket_email_draft_lock,
    heartbeat_ticket_email_draft_lock,
    save_ticket_email_draft,
    upload_ticket_email_draft_attachments,
    delete_ticket_email_draft_attachment,
    discard_ticket_email_draft,
    send_ticket_email_draft,
    get_dashboard_kpi,
    transition_ticket,
    approve_ticket_change,
    list_ticket_approvals,
    get_ticket_workflow,
    reply_ticket_email,
    get_ticket_emails,
    upload_ticket_attachments,
    list_ticket_attachments,
    get_ticket_attachment_for_download,
    get_timeline,
    get_stats,
    get_assignment_timeline,
    # Private helpers defined in _crud
    _workflow_next,
    _workflow_can_transition,
    _normalize_transition_target,
    _is_estado_en_progreso,
    _filter_waiting_subestados,
    _validate_main_status_transition,
    _comment_with_prefix_exists,
    _emit_system_comment,
    _latest_approval_decisions,
    _is_open_estado,
    _evaluate_ticket_sla,
    _maybe_mark_first_response,
    _hydrate_ticket_runtime,
    _find_customer_by_email,
    _get_active_email_draft_row,
    _list_email_draft_attachments,
    _ensure_active_email_draft,
    _serialize_email_draft,
    _ensure_can_edit_email_draft,
    _validate_draft_lock,
    _acquire_draft_lock,
    _normalize_draft_to_email,
    _build_ticket_reply_body_html,
    _prepare_uploaded_reply_attachments,
    _send_ticket_reply_email,
    _html_to_text,
    _parse_attachments_json,
    _normalize_incoming_email_content_id,
    _sanitize_incoming_email_numeric_attr,
    _sanitize_incoming_email_url,
    _sanitize_incoming_email_attr,
    _sanitize_incoming_email_html,
    _plain_text_to_email_html,
    _incoming_email_attachment_inline_url,
    _rewrite_incoming_email_inline_sources,
    _build_incoming_email_body_html,
    _persist_incoming_attachments,
    _assignment_phase_from_subestado,
    _build_assignment_segments,
)

# ── _email: incoming email processing ────────────────────────────────────────
from ._email import (  # noqa: F401
    should_schedule_auto_reply,
    schedule_auto_reply_for_ticket,
    handle_incoming_email,
    _extract_message_ids,
    _message_id_variants,
    _normalize_message_id,
    _normalize_message_ids,
    _merge_reference_chain,
    _build_ticket_thread_headers,
    _update_ticket_thread_metadata,
    _find_ticket_by_thread_headers,
    _find_ticket_by_subject,
    _auto_reply_subject_default,
    _auto_reply_subject,
    _auto_reply_body,
    _process_reply_email,
    _process_new_email_ticket,
)

# ── _customers: client association and directory ──────────────────────────────
from ._customers import (  # noqa: F401
    associate_email_to_client,
    bulk_assign_customer_by_email,
    search_customers,
    get_client_for_email,
    get_directorio_clientes,
    get_directorio_metricas,
)
