"""Initial Baseline

Revision ID: 80882ab55f30
Revises:
Create Date: 2026-03-05 21:22:37.977396

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "80882ab55f30"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_programacion_tareas_id"), table_name="programacion_tareas")
    op.drop_table("programacion_tareas")
    op.drop_index(op.f("ix_bridge_messages_id"), table_name="bridge_messages")
    op.drop_index(op.f("ix_bridge_messages_kind"), table_name="bridge_messages")
    op.drop_index(op.f("ix_bridge_messages_to_agent"), table_name="bridge_messages")
    op.drop_table("bridge_messages")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bridge_messages",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("kind", sa.VARCHAR(), nullable=True),
        sa.Column("title", sa.VARCHAR(), nullable=True),
        sa.Column("body", sa.VARCHAR(), nullable=True),
        sa.Column("from_agent", sa.VARCHAR(), nullable=True),
        sa.Column("to_agent", sa.VARCHAR(), nullable=True),
        sa.Column("status", sa.VARCHAR(), nullable=True),
        sa.Column("payload", sa.VARCHAR(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bridge_messages_to_agent"),
        "bridge_messages",
        ["to_agent"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bridge_messages_kind"), "bridge_messages", ["kind"], unique=False
    )
    op.create_index(
        op.f("ix_bridge_messages_id"), "bridge_messages", ["id"], unique=False
    )
    op.create_table(
        "programacion_tareas",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("plan_id", sa.INTEGER(), nullable=True),
        sa.Column("asignacion_id", sa.INTEGER(), nullable=True),
        sa.Column("fecha", sa.DATE(), nullable=True),
        sa.Column("nota", sa.VARCHAR(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asignacion_id"],
            ["asignaciones_plan.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["planes_trabajo.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asignacion_id", "fecha", name=op.f("uq_prog_asig_fecha")),
    )
    op.create_index(
        op.f("ix_programacion_tareas_id"), "programacion_tareas", ["id"], unique=False
    )
    # ### end Alembic commands ###
