"""Add descripcion_interna to Proyecto

Revision ID: e96b12de3437
Revises: 80882ab55f30
Create Date: 2026-03-05 21:23:16.443300

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e96b12de3437"
down_revision: Union[str, Sequence[str], None] = "80882ab55f30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "proyectos", sa.Column("descripcion_interna", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("proyectos", "descripcion_interna")
    # ### end Alembic commands ###
